export const REQUEST_ALIVE_START = 'REQUEST_ALIVE_START';
export const REQUEST_ALIVE_SUCCESS = 'REQUEST_ALIVE_SUCCESS';
export const REQUEST_ALIVE_FAIL = 'REQUEST_ALIVE_FAIL';
export const REQUEST_ROBOTS_START = 'REQUEST_ROBOTS_START';
export const REQUEST_ROBOTS_SUCCESS = 'REQUEST_ROBOTS_SUCCESS';
export const REQUEST_ROBOTS_FAIL = 'REQUEST_ROBOTS_FAIL';
