export const REQUEST_AUTH_START = 'REQUEST_AUTH_START';
export const REQUEST_AUTH_SUCCESS = 'REQUEST_AUTH_SUCCESS';
export const REQUEST_AUTH_FAIL = 'REQUEST_AUTH_FAIL';
export const REQUEST_LOGOUT_START = 'REQUEST_LOGOUT_START';
export const REQUEST_LOGOUT_SUCCESS = 'REQUEST_LOGOUT_SUCCESS';
export const REQUEST_LOGOUT_FAIL = 'REQUEST_LOGOUT_FAIL';
