export const REQUEST_UPDATE_USER_START = 'REQUEST_UPDATE_USER_START';
export const REQUEST_UPDATE_USER_SUCCESS = 'REQUEST_UPDATE_USER_SUCCESS';
export const REQUEST_UPDATE_USER_FAIL = 'REQUEST_UPDATE_USER_FAIL';
export const REQUEST_USERS_START = 'REQUEST_USERS_START';
export const REQUEST_USERS_SUCCESS = 'REQUEST_USERS_SUCCESS';
export const REQUEST_USERS_FAIL = 'REQUEST_USERS_FAIL';
