export const REQUEST_UPDATE_USER_START = 'REQUEST_UPDATE_USER_START';
export const REQUEST_UPDATE_USER_SUCCESS = 'REQUEST_UPDATE_USER_SUCCESS';
export const REQUEST_UPDATE_USER_FAIL = 'REQUEST_UPDATE_USER_FAIL';
